var BASE_URL = 'http://stomp.api.local';
export default {
  BASE_URL: BASE_URL,
  LOGIN_URL: BASE_URL + '/Login',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  STOMP_JWT: 'STOMP_JWT',
  STOMP_USER: 'STOMP_USER',
  STOMP_SERVER: 'STOMP_SERVER'
}