export default {
  	ADD_ITEM: 'add_item',
    REMOVE_ITEM: 'remove_item',
    REMOVE_ALL: 'remove_all',
    UPDATE_CHECKIN_QUANTITY: ' UPDATE_CHECKIN_QUANTITY',
	REMOVE_CHECKIN_ITEM: 'REMOVE_CHECKIN_ITEM',
	REFRESH: 'REFRESH',
	REMOVE_CHECKIN_ALL: 'REMOVE_CHECKIN_ALL'
}